name: 1 - hello - world

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello world"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print say hi to you
              run: echo "Say hi to you"


            - name: i will suc.
              run: exit 0

            - name: say Goodbye
              run: echo "Goodbye"
              
