name: 3- Simple API call

on:
  push:
  schedule:
   - cron: '30 12 * * *' 
   - cron: '35 12 * * *'
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch data
        run: |
          TIMESTAMP=$(date +%s)
          OUTPUT_FILE="stage/${TIMESTAMP}.csv"
          mkdir -p stage
          curl -s --compressed -H "User-Agent: Chrome/123.0" https://api.coinlore.net/api/tickers/ | jq -r '.data[] | [.id, .symbol, .name, .rank, .price_usd] | @csv'> $OUTPUT_FILE
          echo "Data saved to $OUTPUT_FILE"

      - name: Commit and push changes
        run: |
          git config --local user.email "fozouni@hotmail.com"
          git config --local user.name "fozouni"
          git add stage/
          git commit -m "Fetch data at $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
